import Navbar from "./Navbar/Navbar";
import Footer from "./Footer/Footer";
import Head from "next/head";

export default function Layout({ children }) {
  return (
    <div className="w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@200;300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Navbar />
      <main className="w-full min-h-screen">{children}</main>
      <Footer />
    </div>
  );
}
