import Navbar from "./Navbar/Navbar";
import Footer from "./Footer/Footer";
import Head from "next/head";

export default function Layout({ children }) {
  return (
    <div className="w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Navbar />
      <main className="w-full min-h-screen">{children}</main>
      <Footer />
    </div>
  );
}
