export const blogPosts = [
  {
    coverImage: "/image-blog-1.png",
    avatar: "/avatar.png",
    name: "Darshan Thakker",
    title: "The ultimate checklist you need to get started in Tech",
    category: "Technology",
    views: "233",
    duration: "4 min",
    date: "Feb 28, 2023",
    link: "",
  },
  {
    coverImage: "/image-blog-2.png",
    avatar: "/avatar.png",
    name: "Darshan Thakker",
    title: "The ultimate checklist you need to get started in Tech",
    category: "Technology",
    views: "233",
    duration: "4 min",
    date: "Feb 28, 2023",
    link: "",
  },
  {
    coverImage: "/image-blog-3.png",
    avatar: "/avatar.png",
    name: "Darshan Thakker",
    title: "The ultimate checklist you need to get started in Tech",
    category: "Technology",
    views: "233",
    duration: "4 min",
    date: "Feb 28, 2023",
    link: "",
  },
  {
    coverImage: "/image-blog-4.png",
    avatar: "/avatar.png",
    name: "Darshan Thakker",
    title: "The ultimate checklist you need to get started in Tech",
    category: "Technology",
    views: "233",
    duration: "4 min",
    date: "Feb 28, 2023",
    link: "",
  },
  {
    coverImage: "/image-blog-5.png",
    avatar: "/avatar.png",
    name: "Darshan Thakker",
    title: "The ultimate checklist you need to get started in Tech",
    category: "Technology",
    views: "233",
    duration: "4 min",
    date: "Feb 28, 2023",
    link: "",
  },
  {
    coverImage: "/image-blog-6.png",
    avatar: "/avatar.png",
    name: "Darshan Thakker",
    title: "The ultimate checklist you need to get started in Tech",
    category: "Technology",
    views: "233",
    duration: "4 min",
    date: "Feb 28, 2023",
    link: "",
  },
];
